blog/accounts/urls.py
from django.urls import path,include
from . import views


app_name ="accounts"
urlpatterns = [
    path("login/",views.login_view,name="login"),
    path("logout/",views.logout_view,name="logout"),
    path("register/",views.register_view,name="register"),

]
  
  

  



  

blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("posts.urls",namespace="home")),
    path("",include("accounts.urls",namespace="accounts")),
    path('api/auth/token-auth/',obtain_jwt_token),
    path("api/",include("posts.api.urls",namespace="api")),
    path("api/accounts/",include("accounts.api.urls",namespace="api_accounts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/posts/api/urls.py
from django.urls import path,include
from . import views
from .views import *

app_name ="post"
urlpatterns = [
path("list",PostListAPiView.as_view(),name="list"),
path("create",PostCreateApiView.as_view(),name="create"),
path("details/<str:slug>",PostDetailApiView.as_view(),name="detail"),
path("update/<str:slug>",PostUpdateApiView.as_view(),name="update"),
path("delete/<str:slug>",PostDeleteApiView.as_view(),name="delete"),
path("comments",CommentListAPiView.as_view(),name="comments"),
path("comments/detail/<id>",CommentDetailAPiView.as_view(),name="comment_detail"),
path("comments/update/<id>",CommentUpdateApiView.as_view(),name="comment_update"),
path("comments/delete/<id>",CommentDeleteApiView.as_view(),name="comment_delete"),


]
  
  

  

blog/posts/urls.py
from django.urls import path,include
from . import views


app_name ="post"
urlpatterns = [
    path("create/",views.post_create,name="post"),
    path("details/<str:slug>/",views.post_detail,name="details"),
    path("list/",views.post_list,name="list"),
    path("update/<str:slug>/",views.post_update,name="update"),
    path("delete/<str:slug>/",views.post_delete,name="delete"),
    path("delete_comment/<str:slug>/<id>/",views.comment_delete,name="comment_delete"),
    path("comment_page/<str:slug>/<id>/",views.comment_page,name="comment_page"),


]
  
  

  

blog/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.utils.text import slugify
from .utils import unique_slug_generator
from ckeditor.fields import RichTextField
# Create your models here.


def upload_location(instance,filename):
    filebase,extension = filename.split(".")
    return "%s/%s.%s" %(instance.title,instance.title,extension)

class Post(models.Model):
    user = models.ForeignKey(User,default=1,on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    body = RichTextField(blank=True,null=True)
  #  content = models.TextField() 
    updated = models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)
    image = models.ImageField(upload_to=upload_location,null=True, blank=True,default="index.png")
    slug = models.SlugField(null=True,unique=True,blank=True)
    

    def __str__(self):
        return self.title

    def post_count(user):
        return Post.objects.filter(user=user).count()

    class Meta:
        ordering =["-timestamp"] 


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Post)
'''
    def save(self,*args,**kwargs):
        if Post.objects.filter(title=self.title).exists():
            unique_slug = str(self.user.id)
            self.slug = slugify(self.title)+"-"+unique_slug
            save() 
        else:
            self.slug = slugify(self.title) 
        super(Post,self).save(*args,**kwargs)
'''
class Comments(models.Model):
    post = models.ForeignKey(Post,related_name="comments",on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE) 
    content = models.TextField()
    reply = models.ForeignKey("Comments", null= True, related_name="replies",on_delete=models.CASCADE)  
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)

     

    def __str__(self):
        return self.post.title


'''
def pre_save_post_receiver(sender,instance,*args,**kwargs):
    slug = slugify(instance.title)
    exists = Post.objects.filter(slug=slug).exists() 
    if exists:
        slug = "%s-%s"%(slug,instance.id)
    instance.slug = slug

pre_save.connect(pre_save_post_receiver,sender=Post)
'''

blog/posts/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title","body","image"]


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea,label="")
    class Meta:
        model = Comments
        fields = ["content"]

blog/posts/api/views.py
from django_filters.rest_framework import DjangoFilterBackend

from rest_framework.generics import(
ListAPIView,RetrieveAPIView,UpdateAPIView,DestroyAPIView,CreateAPIView,
RetrieveUpdateAPIView
)
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)
from .permissions import *
from .serializers import *
from posts.models import Post
from .pagination import *

class PostCreateApiView(CreateAPIView):
    queryset= Post.objects.all()
    serializer_class = PostCreateSerializers
    permission_classes= [IsAuthenticated]
    def perform_create(self,serializer):
        serializer.save(user=self.request.user)

class PostDetailApiView(RetrieveAPIView):
    queryset= Post.objects.all()
    serializer_class = PostDetailSerializers
    permission_classes= [IsAuthenticated]

    lookup_field="slug"

class PostUpdateApiView(RetrieveUpdateAPIView):
    queryset= Post.objects.all()
    serializer_class = PostDetailSerializers
    permission_classes= [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]

    lookup_field="slug"
   # def perform_update(self,serializer):
    #    serializer.save(user=self.request.user)

class PostDeleteApiView(DestroyAPIView):
    queryset= Post.objects.all()
    serializer_class = PostDetailSerializers
    permission_classes= [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]
    lookup_field="slug"

 
 
class PostListAPiView(ListAPIView):
    queryset= Post.objects.all()
    serializer_class = PostListSerializers
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['body', 'title']
    pagination_class = CustomPagination


class CommentListAPiView(ListAPIView):
    queryset= Comments.objects.filter(reply=None)
    serializer_class = CommentListSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['post', 'content']
    pagination_class = CustomPagination

class CommentDetailAPiView(RetrieveAPIView):
    queryset= Comments.objects.all()
    serializer_class = CommentDetailSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['post', 'content']
    pagination_class = CustomPagination
    lookup_field = "id"
    many= True

'''
class CommentCreateApiView(CreateAPIView):
    queryset= Comments.objects.all()
    serializer_class = CommentCreateSerializers
    permission_classes= [IsAuthenticated]
    def perform_create(self,serializer):
        serializer.save(user=self.request.user,post=self.Post)
'''

class CommentUpdateApiView(RetrieveUpdateAPIView):
    queryset= Comments.objects.all()
    serializer_class = CommentDetailSerializer
    permission_classes= [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]
    lookup_field = "id"

class CommentDeleteApiView(DestroyAPIView):
    queryset= Comments.objects.all()
    serializer_class = CommentDetailSerializer
    permission_classes= [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]
    lookup_field="id"

 

blog/posts/views.py
from django.shortcuts import render,redirect,Http404
from django.shortcuts import get_object_or_404
from django.db.models import Count    
from django.core.paginator import Paginator
from django.contrib import messages
from django.utils import timezone
from django.urls import reverse
from .models import *
from .forms import *
from .filters import *

from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url="/login/") #you can you settings to make a default login 
def post_create(request):
    form = PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request,"Post Created Successfully")
        return redirect(reverse("home:details",kwargs={"slug":instance.slug}))

 #   if request.method =="POST":
  #      print("content is " + request.POST.get("content"))
    context={"form":form}
    return render(request,"post_form.html",context)
 


def post_detail(request,slug):          #retrive
    instance = Post.objects.get(slug=slug)
    comments = Comments.objects.filter(post=instance,reply=None).order_by("-id")
    if request.method =="POST":
        form = CommentForm(request.POST or None,instance=instance)
        if form.is_valid():
            content = request.POST.get("content")
            reply_id = request.POST.get("comment_id")
            comment_qs = None 
            if reply_id:
                comment_qs = Comments.objects.get(id=reply_id)
            comment = Comments.objects.get_or_create(post=instance, user=request.user,content=content,reply=comment_qs)
            form.save()
            return redirect(reverse("home:details",kwargs={"slug":instance.slug}))
           
    else:
        form=CommentForm(None)
    context ={"instance":instance,"comments":comments,"form":form}
    return render(request,"post_detail.html",context)



def post_list(request):          #list items
    instance = Post.objects.all()
    user_posts = User.objects.annotate(total_posts = Count('post'))
    my_posts = Post.objects.filter(user=request.user).count
    post_filter = PostFilter(request.GET,queryset=instance)
    instance = post_filter.qs 

    paginator = Paginator(instance,6) # Show 5 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context ={"objects":page_obj,"myfilter":instance,"user_posts":user_posts,"my_posts":my_posts}
    return render(request,"post_list.html",context)

@login_required(login_url="/login/")
def post_update(request,slug):
    instance = Post.objects.get(slug=slug)
    form = PostForm(request.POST or None,request.FILES or None,instance=instance)
    if instance.user != request.user:
        raise Http404
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request,"updated")
        return redirect(reverse("home:details",kwargs={"slug":slug}))
    context ={"instance":instance,"form":form}
    return render(request,"post_form.html",context)

def post_delete(request,slug):
    instance = Post.objects.get(slug=slug)
    if instance.user != request.user:
        raise Http404
    if request.method =="POST":
        instance.delete()
        return redirect("/list")
    context = {"instance":instance}
    return render(request,"post_delete.html",context)

@login_required(login_url="/login/")
def comment_delete(request,id,slug):
    instance = Comments.objects.get(id=id)
    post = Post.objects.get(slug=instance.post.slug)
    if instance.user != request.user:
        raise Http404
    if request.method =="POST":
        instance.delete()
        return redirect(reverse("home:details",kwargs={"slug":post.slug}))
    context = {"instance":instance} 
    return render(request,"comment_delete.html",context)

@login_required(login_url="/login/")
def comment_page(request,id,slug):
    instance = Comments.objects.get(id=id)
    post = Post.objects.get(slug=instance.post.slug)
    comments = Comments.objects.filter(post=post ).order_by("-id")
    if request.method =="POST":
        form = CommentForm(request.POST or None,instance=post)
        if form.is_valid():
            content = request.POST.get("content")
            reply_id = request.POST.get("comment_id")
            comment_qs = None 
            if reply_id:
                comment_qs = Comments.objects.get(id=reply_id)
            comment = Comments.objects.get_or_create(post=post, user=request.user,content=content,reply=comment_qs)
            form.save()
            return redirect(reverse("home:comment_page",kwargs={"id":instance.id,"slug":instance.post.slug}))
           
    else:
        form=CommentForm(None)
    context = {"comments":comments,"form":form,"instance":instance} 
    return render(request,"comment_page.html",context)







    

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!-- THIS LINE -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">


<body>

        
    {% block content %}
    
    {% endblock %}
<script>

    $(document).ready(function () {
        $("#toggle").click(function () {
            $("div").toggleClass("hidden unhidden");
        });
    });
</script>

    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v9.0" nonce="A0j0eiei"></script>

<!-- JAVASCRIPT  Here-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

</body>

blog/templates/messages_display.html
<div class="container">

    {% if messages %}

    <div class="alert alert-success">
        {% for message in messages %}
        <strong>{{ message.tags|upper }} {{ message }}</strong>
      </div>
{% endfor %}
{% endif %}

blog/templates/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block content %}
<title>{{instance.title}}</title> 

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:list' %}">List</a>
      {% if instance.user == request.user %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:update' slug=instance.slug %}">Update</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:delete' slug=instance.slug %}">Delete</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </div>
  </nav>


  <div class="container">
    <div class="row">
        <h2>{{instance.title}} </h2>
        <p>Created By {{instance.user.get_full_name|title}} since : <small>{{instance.updated|timesince}}</small></p>
     
    
          {% include 'messages_display.html' %}
      
        
        <div class="col col-lg-6 col-md-12 col-sm-12">
          {% if instance.image %}
          <img src="{{instance.image.url}}"  alt="image-field" width='300px' class="img-thumbnail">
          {% else %}
          <img src="{% static 'default.png' %}"  alt="image-field" width='300px' class="img-thumbnail">
            {% endif %}
          </div>
        <hr>
    </div>
  </div>

  <div class="container">
<div class="row">
  <div class="col col-lg-6 col-md-6 col-sm-12">
    <h3>Content:</h3>
    {{instance.body|safe}} 
</div>
</div>
</div>

<div class="container">
  <div class="col col-lg-6 col-md-12 col-sm-12">
    <a class="btn btn-primary btn-sm"  role="button" href="https://www.facebook.com/sharer/sharer.php?u={% url 'home:details' slug=instance.slug %}">Share on Facebook</a>

    <a  class="btn btn-primary btn-sm"  role="button" href="https://plus.google.com/share?url={% url 'home:details' slug=instance.slug %}">Share on Google+</a>
    <a  class="btn btn-primary btn-sm"  role="button" href="https://www.linkedin.com/shareArticle?mini=true&url=http://swiftforentrepreneurs.com/&title={{instance.content|urlify}}">
        Share on Linkedin</a>    
  </div>

</div>
<hr>
<div class="container">
    <div class="row">
<!-- {{instance.content|truncatechars:10|urlify}}-->


<div class="col col-lg-6 col-md-6 col-sm-12" id="comment" >
  <h2>
   Create a comment
  </h2>
{% if request.user.is_authenticated %}
    <form method="POST">
      {% csrf_token %}
{{form|crispy}}
<input class="btn btn-primary"  type="submit" value="submit" >
   {% else %}
   <p class="lead">Login To Comment on Post</p>
   {% endif %}
      <!--
      <div class="form-group validate-input" data-validate="Cant be Zero">
        <textarea class="form-control" placeholder="Create Your Comment" name="content" rows="2"> </textarea>
        {% for err in form.content.errors %}
        <small class="text-danger">{{err}}</small>
        {% endfor %}
        <br>
        <input class="btn btn-primary" type="submit" value="submit" >
   
      </div>
-->
    
    </form>

 
</div>
</div>
</div>
  <hr>
  


  <div class="container">
<div class="row">
  {% for comment in comments %}
<div class="col col-lg-6 col-md-12 col-sm-12">

  <figure class="text-left">
    <blockquote class="blockquote">
      <p>{{comment.content}}</p>
    </blockquote>
    <figcaption class="blockquote-footer">
      Created By <cite title="Source Title">{{comment.user.get_full_name|title}} Since {{comment.timestamp|timesince}}</cite>
    </figcaption>
  </figure>

</div>
<div class="col col-lg-12 col-md-12 col-sm-12">

  <p>{{comment.replies.all.count}} comments|  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#{{comment.id}}" aria-expanded="false" aria-controls="{{comment.id}}">
    Reply
   </button>

{% if request.user.id == comment.user.id %}
   <a href="{% url 'home:comment_delete' slug=comment.post.slug  id=comment.id %}">delete</a>
   {% endif %}
   <a href="{% url 'home:comment_page' slug=comment.post.slug  id=comment.id %}">share</a>

  </p>  


  </div>

   <div class="collapse container at-2"  id="{{comment.id}}">
    <h3>Replies</h3>  
    {% if comment.replies.all %}
     {% for reply in comment.replies.all %}
     <blockquote class="blockquote">
      <p class="mb-0"> {{reply.content}}</p>
      <footer class="blockquote-footer">by {{reply.user.get_full_name|title}} since {{reply.timestamp|timesince}}</cite></footer>
    </blockquote>
  {% endfor %}
    {% else %}
    <blockquote class="blockquote">
      <p class="mb-0">No Replies Yet</p>
    </blockquote>
     {% endif %}
<div class="col col-lg-6">

  <div class="form-group row">
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" placeholder="Reply to Comment" name="content" rows="2" col="1"></textarea>
        <input type="hidden" name="comment_id"  value="{{comment.id}}">
                {% for err in form.content.errors %}
          <small class="text-danger">{{err}}</small>
          {% endfor %}
          <br>
        <input class="btn btn-primary" type="submit" value="Reply" >
      </div>
  
    </form>
 
</div>

</div>

   </div>

 

  <hr> 

  {% endfor %}
  </div>


  </div>







<!--
<div class="fb-comments" data-numposts="5" data-href="http://{{ request.META.HTTP_HOST }}{% url 'home:details' slug=instance.slug %}"></div>
<div class="fb-like" data-href="{% url 'home:details' slug=instance.slug %}" data-width="" data-layout="standard" data-action="like" data-size="large" data-share="true"></div>
-->


{% endblock %}

blog/templates/post_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}


<title>Create a Post</title>


{% block content %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:list' %}">List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

      </ul>
    </div>
  </div>
</nav>

  <div class="container">
        <div class="row">
          <div class="col col-lg-6">
            <form method="POST" action="" enctype='multipart/form-data'>
              {% csrf_token %}
              <div class="col col-lg-12">
       {% crispy form %}
          <button class="btn btn-dark" type="submit">Done</button>
           
              </div>    
  
  </form>
              </div>
            </div>
          </div>




 

{% endblock %}

blog/templates/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block content %}

<title>List</title>


{% for user in user_posts %}
{{user.username}} Got {{ user.total_posts }}

{% endfor %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:list' %}">List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:post'  %}">Create New Post</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">User: {{request.user.get_full_name|title}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Posts: {{my_posts}}</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
        </li>

        {% endif %}
        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:register' %}">Register</a>
        </li>
      

      </ul>
    </div>
  </div>
</nav>
        <div class="container">
          <div class="row">
            <h1>List</h1>
            {% for obj in objects %}
            <div class="col col-lg-4 col-md-6 col-sm-12">
             
              <br>
                  <div class="card-group">
                      <div class="card" style="width: 18rem;">
                        {% if obj.image %}
                        <img src="{{obj.image.url}}" class="card-img-top"  alt="Image">
                        {% else %}
                        <img src="{% static 'index.png' %}"   class="card-img-top"  alt="Image">

                       {% endif %}
                        <div class="card-body">
                      <a href="{% url 'home:details' slug=obj.slug %}">   <h5 class="card-title"> {{obj.title}}</h5> </a>
                          <p>Author: {{obj.user.get_full_name|title}}</p>
                          <p class="card-text">Content: {{obj.content|safe|truncatechars_html:10}}</p>
                        
                          <p class="card-text"><small class="text-muted">{{instance.updated}}</small></p>
                        </div>
                        <div class="buttons">
                          <a class="btn btn-primary" href="{% url 'home:details' slug=obj.slug %}" role="button">Details</a>        
                        </div>
                      </div>
                  
                    </div>
              </div>
              
              {% endfor %}
            </div>

        {% if objects.has_other_pages %}



        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if objects.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{objects.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% endif %}
            {% for i in objects.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endfor %}
            {% if objects.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{objects.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>

        {% endif %}



              

        
          </div>



  
<!--
            <ul class="pagination">
               
                <li class="page-item">
               
                  {% if objects.has_previous %}
                  <span class="page-item">Previous</span>
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                  {% endif %}
                </a>
              
              </li>

              <li class="page-item active" aria-current="page">
                <span class="page-item">{{objects.page_number}}</span>
              </li>

               
                <li class="page-item">
                  <span class="page-item">Next</span>
                  {% if objects.has_next %}
                <a class="page-link" href="?page={{ objects.next_page_number }}">
              </a>
              {% endif %}
           </li>
             
            </ul>
-->

{% endblock %}

blog/templates/update_form.html
{% extends "base.html" %}
{% load static %}
{% load urlify %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
<div class="container">
<div class="row">
    {% block content_media %}
    {{ form.media }}
    {% endblock %}
     
</div>


</div>


{% block content %}
<title>{{instance.title}}</title> 

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:list' %}">List</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:delete' slug=instance.slug %}">Delete</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container">
    <div class="row">
      <div class="col col-lg-12">
        <form method="POST" action="" enctype='multipart/form-data'>
            {% csrf_token %}
           
                {% cripsy form %}
         


</div>
<br>
              <button type="submit" class="btn btn-dark">Submit</button>
            </form>
      </div>

  </div>





{% endblock %}